# Dockerfile-envio
FROM kalilinux/kali-rolling

# Instalar herramientas necesarias
RUN apt-get update --fix-missing && \
    apt-get install -y --no-install-recommends openssl zip sshpass openssh-client && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Crear directorio de trabajo
WORKDIR /home/cloud-user

# Copiar el archivo .txt al contenedor
COPY compras-22-09-2024.txt /home/cloud-user/compras-22-09-2024.txt

# Copiar el script de envío
COPY script.sh /usr/local/bin/script.sh

# Dar permisos de ejecución al script
RUN chmod +x /usr/local/bin/script.sh

# Comando por defecto para ejecutar el script de envío
CMD ["/usr/local/bin/script.sh", "compras-22-09-2024.txt", "servidor_ssh"]